### ISSUE TITLE
header compatibility

### ISSUE THREAD

**Issue by verga** [ashwinvis/myst-reader#12]
I have a pelican site with about 60 articles: should I reformat all headers to YAML if I want to use myst?
Actually I tried it but I get an error complaining about the front-matter for each page. 

A second question: I use a lot of math through the `render_math` (mathjax) plugin; is it necessary to keep it with myst? 

Thank you.

**Comment by ashwinvis** [comment]
@verga sorry for the late response. Yes, you need YAML frontmatter to use myst, but as mentioned in the readme, you can Titlecase the keys, so that it works also with regular Markdown plugin.

Myst supports math so you dont need an extra plugin. You may have to ensure mathjax or katex source files are served.

**Comment by verga** [comment]
Thank you!
